---@type LazySpec 
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "org",
      "bash",
      "c",
      "dockerfile",
      "python",
      "rust",
      "lua",
      "go",
      "java",
      "gomod",
      "gowork",
      "gosum",
      "json",
      "json5",
      "jsonc",
      "typescript",
      "javascript",
      "rasi",
      "tsx",
      "yaml",
      "regex",
      "markdown",
      "markdown_inline",
    },
  },
}
